// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TournamentMS.Infrastructure.Data;

#nullable disable

namespace TournamentMS.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    [Migration("20250220002715_schema")]
    partial class schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TournamentMS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alias");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("code");

                    b.Property<int?>("LimitParticipant")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alias = "Racing",
                            Code = "0235",
                            Name = "Carreras"
                        });
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCooperative")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxPlayersPerTeam")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("Players")
                        .HasColumnType("integer")
                        .HasColumnName("players");

                    b.HasKey("Id");

                    b.ToTable("games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCooperative = false,
                            MaxPlayersPerTeam = 0,
                            MaxTeams = 0,
                            Name = "Need For Speed",
                            Players = 10
                        });
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Prize", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdTournament")
                        .HasColumnType("integer");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Prize");
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("IdCategory")
                        .HasColumnType("integer")
                        .HasColumnName("id_category");

                    b.Property<int>("IdGame")
                        .HasColumnType("integer")
                        .HasColumnName("id_game");

                    b.Property<int>("IdOrganizer")
                        .HasColumnType("integer")
                        .HasColumnName("id_organizer");

                    b.Property<int>("IdPrize")
                        .HasColumnType("integer")
                        .HasColumnName("id_prize");

                    b.Property<int?>("IdTeamWinnerTournament")
                        .HasColumnType("integer")
                        .HasColumnName("id_team_winner_tournmanent");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_free");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tournament_status");

                    b.HasKey("Id");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdGame");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.TournamentUserRole", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("integer")
                        .HasColumnName("id_user");

                    b.Property<int>("IdTournament")
                        .HasColumnType("integer")
                        .HasColumnName("id_tournament");

                    b.Property<int>("IdRole")
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    b.HasKey("IdUser", "IdTournament", "IdRole");

                    b.HasIndex("IdTournament");

                    b.ToTable("tournaments_users_roles", (string)null);
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Prize", b =>
                {
                    b.HasOne("TournamentMS.Domain.Entities.Tournament", "Tournament")
                        .WithOne("Prize")
                        .HasForeignKey("TournamentMS.Domain.Entities.Prize", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("TournamentMS.Domain.Entities.Category", "Category")
                        .WithMany("Tournaments")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentMS.Domain.Entities.Game", "Game")
                        .WithMany("Tournaments")
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.TournamentUserRole", b =>
                {
                    b.HasOne("TournamentMS.Domain.Entities.Tournament", null)
                        .WithMany("UsersTournamentRole")
                        .HasForeignKey("IdTournament")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Game", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("TournamentMS.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Prize")
                        .IsRequired();

                    b.Navigation("UsersTournamentRole");
                });
#pragma warning restore 612, 618
        }
    }
}
